/*
 *      Author: Ahmed Ali
 *      Email:  Ahmali777@gmail.com
 */

#include"TMR1_int.h"
#include <avr/interrupt.h>

/****** Global Pointer To Function *********/
static void (*GPFunc_OVF)(void)=NULL;
static void (*GPFunc_OCA)(void)=NULL;



void TMR1_voidSetOVFCallBack(void(*LocPFunc)(void))
{
	GPFunc_OVF=LocPFunc;
}
void TMR1_voidSetOCACallBack(void(*LocPFunc)(void))
{
	GPFunc_OCA=LocPFunc;
}


ISR(TIMER1_COMPA_vect)
{
	if(GPFunc_OCA!=NULL)
	{
		GPFunc_OCA();
	}

}

ISR(TIMER1_OVF_vect)
{
	if(GPFunc_OVF!=NULL)
	{
		GPFunc_OVF();
	}

}







void TMR1_voidInit(void)
{
	/*********************TIMER 1 MODE*************************/
#if TIMER1_MODE == TMR1_NORMAL
	CLR_BIT(TCCR1A,WGM10);
	CLR_BIT(TCCR1A,WGM11);
	CLR_BIT(TCCR1B,WGM12);
	CLR_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_PWM_PC_8BIT
	SET_BIT(TCCR1A,WGM10);
	CLR_BIT(TCCR1A,WGM11);
	CLR_BIT(TCCR1B,WGM12);
	CLR_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_PWM_PC_9BIT
	CLR_BIT(TCCR1A,WGM10);
	SET_BIT(TCCR1A,WGM11);
	CLR_BIT(TCCR1B,WGM12);
	CLR_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_PWM_PC_10BIT
	SET_BIT(TCCR1A,WGM10);
	SET_BIT(TCCR1A,WGM11);
	CLR_BIT(TCCR1B,WGM12);
	CLR_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_CTC_OCR1A_TOP
	CLR_BIT(TCCR1A,WGM10);
	CLR_BIT(TCCR1A,WGM11);
	SET_BIT(TCCR1B,WGM12);
	CLR_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_FAST_PWM_8BIT
	SET_BIT(TCCR1A,WGM10);
	CLR_BIT(TCCR1A,WGM11);
	SET_BIT(TCCR1B,WGM12);
	CLR_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_FAST_PWM_9BIT
	CLR_BIT(TCCR1A,WGM10);
	SET_BIT(TCCR1A,WGM11);
	SET_BIT(TCCR1B,WGM12);
	CLR_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_FAST_PWM_10BIT
	SET_BIT(TCCR1A,WGM10);
	SET_BIT(TCCR1A,WGM11);
	SET_BIT(TCCR1B,WGM12);
	CLR_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_PC_FC_ICR1
	CLR_BIT(TCCR1A,WGM10);
	CLR_BIT(TCCR1A,WGM11);
	CLR_BIT(TCCR1B,WGM12);
	SET_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_PC_FC_OCR1A
	SET_BIT(TCCR1A,WGM10);
	CLR_BIT(TCCR1A,WGM11);
	CLR_BIT(TCCR1B,WGM12);
	SET_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_PC_ICR1
	CLR_BIT(TCCR1A,WGM10);
	SET_BIT(TCCR1A,WGM11);
	CLR_BIT(TCCR1B,WGM12);
	SET_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_PC_OCR1A
	SET_BIT(TCCR1A,WGM10);
	SET_BIT(TCCR1A,WGM11);
	CLR_BIT(TCCR1B,WGM12);
	SET_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_CTC_ICR1_TOP
	CLR_BIT(TCCR1A,WGM10);
	CLR_BIT(TCCR1A,WGM11);
	SET_BIT(TCCR1B,WGM12);
	SET_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_FAST_PWM_ICR1
	CLR_BIT(TCCR1A,WGM10);
	SET_BIT(TCCR1A,WGM11);
	SET_BIT(TCCR1B,WGM12);
	SET_BIT(TCCR1B,WGM13);
#elif TIMER1_MODE == TMR1_FAST_PWM_OCR1A
	SET_BIT(TCCR1A,WGM10);
	SET_BIT(TCCR1A,WGM11);
	SET_BIT(TCCR1B,WGM12);
	SET_BIT(TCCR1B,WGM13);
#endif

	/*********************TIMER 1 PRESCALER*************************/
	TCCR1B &= 0XF8;
	TCCR1B |=TIMER1_Prescaler ;

	/*********************TIMER0 OC1A MODE*************************/
	TCCR1A &= 0B00111111; //CLEAR OC1A MODE BITS
	TCCR1A |=(TIMER1_OC1A_MODE<<COM1A0);


	/*********************TIMER0 OC1B MODE*************************/
	TCCR1A &= 0B11001111; //CLEAR OC1B MODE BITS
	TCCR1A |=(TIMER1_OC1B_MODE<<COM1B0);

}
void TMR1_voidEnableOVFInterrupt(void)
{
	SET_BIT(TIMSK,TOIE1);
}
void TMR1_voidEnableOCAMInterrupt(void)
{
	SET_BIT(TIMSK,OCIE1A);
}

void TMR1_voidEnableOCBMInterrupt(void)
{
	SET_BIT(TIMSK,OCIE1B);
}




void TMR1_voidSetTimerCounter(u16 Value_of_TCNT1)
{
	TCNT1=Value_of_TCNT1;
}
void TMR1_voidSetOCR1A(u16 Value_of_OCR1A)
{
	OCR1A=Value_of_OCR1A;
}

void TMR1_voidSetOCR1B(u16 Value_of_OCR1B)
{
	OCR1B=Value_of_OCR1B;
}



